### ISSUE TITLE
Test Code

### ISSUE THREAD

**Issue by yanghoon** [hky0715/redis#1]
```bash
curl localhost:8080/api/redis/a:get
curl localhost:8080/api/redis/a:set?val=a
curl localhost:8080/api/redis/a:get
```

```yaml
spring:
  data:
    redis:
      password: bitnami
      cluster:
        nodes: localhost:7004,localhost:7005,localhost:7006
```

```java
@RestController
@RequestMapping("/api/redis")
@RequiredArgsConstructor
public class RedisTest {

    private final StringRedisTemplate redisTemplate;

    @GetMapping("{key}:{ops}")
    public String generateDummyData(
            @PathVariable("ops") String ops,
            @PathVariable("key") String key,
            @RequestParam(name = "val", required = false) String val 
            )  {
        return switch(ops) {
            case "get" -> redisTemplate.opsForValue().get(key);
            case "set" -> {
                redisTemplate.opsForValue().set(key, val);
                yield "OK";
            }
            default -> "NoOps";
        };
    }

    @EventListener
    public void generateDummyData(ApplicationReadyEvent event)  {
        var ops = redisTemplate.opsForValue();
        var val = ops.get("a");
        System.out.println(val);
    }
    
}
```

```yaml
version: '3'
services:
  # redis-node-0:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   container_name: redis00
  #   restart: always
  #   ports:
  #     - 7001:7001
  #     - 17001:17001
  #   environment:
  #     - REDIS_PASSWORD=bitnami
  #     - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
  #   networks:
  #     - redis-cluster-network

  # redis-node-1:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   container_name: redis01
  #   restart: always
  #   ports:
  #     - 7002:7002
  #     - 17002:17002
  #   environment:
  #     - REDIS_PASSWORD=bitnami
  #     - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
  #   networks:
  #     - redis-cluster-network

  # redis-node-2:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   container_name: redis02
  #   restart: always
  #   ports:
  #     - 7003:7003
  #     - 17003:17003
  #   environment:
  #     - REDIS_PASSWORD=bitnami
  #     - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
  #   networks:
  #     - redis-cluster-network

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.2
    container_name: redis03
    restart: always
    ports:
      - 7004:6379
      # - 17004:17004
    environment:
      - REDIS_PASSWORD=bitnami
      # - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - REDIS_NODES=redis-node-3 redis-node-4 redis-node-5
    networks:
      - redis-cluster-network

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.2
    container_name: redis04
    restart: always
    ports:
      - 7005:6379
      # - 17005:17005
    environment:
      - REDIS_PASSWORD=bitnami
      # - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - REDIS_NODES=redis-node-3 redis-node-4 redis-node-5
    networks:
      - redis-cluster-network

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.2
    container_name: redis05
    restart: always
    ports:
      - 7006:6379
      # - 17006:17006
    depends_on:
      # - redis-node-0
      # - redis-node-1
      # - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - REDIS_PASSWORD=bitnami
      - REDISCLI_AUTH=bitnami
      - REDIS_CLUSTER_REPLICAS=0
      # - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - REDIS_NODES=redis-node-3 redis-node-4 redis-node-5
      - REDIS_CLUSTER_CREATOR=yes
    # command: redis-cli --cluster create localhost:7001 localhost:7002 localhost:7003 localhost:7004 localhost:7005 localhost:7006 --cluster-yes
    networks:
      - redis-cluster-network

networks:
  redis-cluster-network:
    driver: bridge
```

**Comment by yanghoon** [comment]
```yaml
version: '3'
services:
  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.2
    container_name: redis03
    restart: always
    environment:
      - REDIS_PASSWORD=bitnami
      - REDIS_NODES=localhost:7004 localhost:7005 localhost:7006
      - REDIS_PORT_NUMBER=7004
    network_mode: host

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.2
    container_name: redis04
    restart: always
    environment:
      - REDIS_PASSWORD=bitnami
      - REDIS_NODES=localhost:7004 localhost:7005 localhost:7006
      - REDIS_PORT_NUMBER=7005
    network_mode: host

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.2
    container_name: redis05
    restart: always
    depends_on:
      - redis-node-3
      - redis-node-4
    environment:
      - REDIS_PASSWORD=bitnami
      - REDISCLI_AUTH=bitnami
      - REDIS_NODES=localhost:7004 localhost:7005 localhost:7006
      - REDIS_PORT_NUMBER=7006
      - REDIS_CLUSTER_REPLICAS=0
      - REDIS_CLUSTER_CREATOR=yes
    network_mode: host
```

**Comment by hky0715** [comment]
```
services:
  redis-cluster:
#    platform: linux/x86_64 # m1 MacOS의 경우
    image: redis:6.2
    container_name: redis-test
    volumes: # 작성한 설정 파일을 볼륨을 통해 컨테이너에 공유
      - ./redis0.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6380:6380
      - 6381:6381
      - 6379:6379

  redis-node-1:
    network_mode: "service:redis-cluster"
#    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-test1
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-2:
    network_mode: "service:redis-cluster"
#    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-test2
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-entry:
    network_mode: "service:redis-cluster"
#    platform: linux/x86_64
    image: redis:6.2
    container_name: redis-cluster-entry
    command: redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-yes
    depends_on:
      - redis-cluster
      - redis-node-1
      - redis-node-2
```
